version: '3'
services:
  dvs_frontend:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    networks:
      - dvs_net

networks:
  dvs_net: